resilience4j:
  circuitbreaker:
    configs:
        defecto:
          sliding-window-size: 6 #cantidad de peticiones para activar la ventana deslizante
          failure-rate-threshold: 50 # tasa de fallo
          wait-duration-in-open-state: 20s # tiempo de espera en estado abierto
          permitted-number-of-calls-in-half-open-state: 4 # cantidad de llamadas permitidas en estado semi abierto
          slow-call-rate-threshold: 50 #tasa de lentitud
          slow-call-duration-threshold: 2s # tiempo de espera considerada una llamada lenta
    instances:
      productos: # nombre del corto circuito definido en ItemConfig
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s #duracion timeout por defecto cortocircuito 
    instances:
      productos:
        base-config: defecto

spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:          
          - Path=/api/productos/**
#          - Header=token, \d+
#          - Header=Content-Type, application/json
#          - Method=GET, POST
#          - Query=color
#          - Cookie=color, azul
        filters:
          - name: CircuitBreaker
            args:
              name: productos
              statusCodes: 500
              fallbackUri: forward:/api/items/ver/9/cantidad/5
          - StripPrefix=2
          - EjemploCookie=Hola mi mensaje personalizado, usuario, FelipeSeguel 
#        - name: Ejemplo
#          args:
#            mensaje: Hola mi mensaje personalizado
#            cookieNombre: usuario 
#            cookieValor: FelipeSeguel
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 12345678
          #- SetResponseHeader=Content-Type, text/plain
          - AddRequestParameter=nombre, andres
      - id: servicio-oauth
        uri: lb://servicio-oauth
        predicates:
          - Path=/api/security/**
        filters:
          - StripPrefix=2
      - id: servicio-usuarios
        uri: lb://servicio-usuarios
        predicates:
          - Path=/api/usuarios/**
        filters:
          - StripPrefix=2
